services:
  app:
    container_name: guessnumber-app
    build:
      context: ../guess-number-app
      dockerfile: Dockerfile
      args:
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    env_file:
      - ../env/.prod.env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - default
      - webnet

  redis:
    image: redis:7-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - redis-data:/data
      - ../config/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: guessnumber-redisinsight
    ports:
      - "127.0.0.1:5540:5540"
    volumes:
      - redisinsight-data:/data
    depends_on:
      - redis
    restart: unless-stopped

networks:
  webnet:
    name: webnet
    external: true

volumes:
  redis-data:
  redisinsight-data:
